GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWVzIiwiaWF0IjoxNzAxMzk3MTE5fQ.-tKE2Yzk5L39H7HQEBxlNPWA45BN-_geafP4Lp6a9lM

###

POST http://localhost:3000/login
Content-type: application/json

{
     "username": "Yes"
}


#####
GET http://localhost:3000/api/user/me/wishlist?id=656c4d3aef4c2d379ceb0163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwMTYwMjA1M30.muWvxmH3V4DjnJmYqjGD_ZuNCsCD1uGfvDB_dKOE5xs


#####
POST http://localhost:3000/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwMTYwMjA1M30.muWvxmH3V4DjnJmYqjGD_ZuNCsCD1uGfvDB_dKOE5xs
Content-Type: application/json

{"id": "65a91e228e15e34cb43a808f", "email": "jason3213123@gmail.com", "first_name": "Keon", "image": "", "last_name": "Kevin"}

###
POST http://localhost:3000/api/add_favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwMTYwMjA1M30.muWvxmH3V4DjnJmYqjGD_ZuNCsCD1uGfvDB_dKOE5xs
Content-Type: application/json

{
    "userId": "656c4d3aef4c2d379ceb0163",
    "category": "oten",
    "product": {
     "oten": "oten"
    }
}

####
POST http://localhost:3000/api/user/me/wishlist
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwMTYwMjA1M30.muWvxmH3V4DjnJmYqjGD_ZuNCsCD1uGfvDB_dKOE5xs

{
     "userId": "656c4d3aef4c2d379ceb0163",
     "list": [
               {
               "_id": "656c12d6e305645d736fd635",
               "category": "Snacks",
               "product": {
                    "title": "Mondelez Oreo Vanilla Cookies | 27.6g 9pcs",
                    "price": 80,
                    "image_url": "https://smmarkets.ph/media/catalog/product/2/0/20232695_oreo_vanilla_27.6g_x_9_pcs_copy_.png?optimize=low&bg-color=255%2C255%2C255&fit=bounds&height=300&width=300"
               }
               }
     ]
}


####
DELETE http://localhost:3000/api/user/me/wishlist
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwMTYwMjA1M30.muWvxmH3V4DjnJmYqjGD_ZuNCsCD1uGfvDB_dKOE5xs

{
     "userId": "656c4d3aef4c2d379ceb0163",
     "id": "656d64c29be7f4d376cdbbfe"
}

#######
PUT http://localhost:3000/api/user/me/wishlist
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwNTEwMDgyMSwiZXhwIjoxNzA1MTA0NDIxfQ.nIqoNxr-4OiXz1DQ_V_dYESsWnX4C2MIkSPpPtkUDzQ

{
     "userId": "656c4d3aef4c2d379ceb0163",
     "id": "656d64d09be7f4d376cdbc03",
     "list":[
           {
          "_id": "656c0b6be305645d736fc695",
          "category": "Frozen Goods",
          "product": {
               "title": "Selecta Choco Almond Fudge Ice Cream - Cookies & Cream Ice Cream | 2L",
               "price": 350,
               "image_url": "https://smmarkets.ph/media/catalog/product/2/0/20520405-1.jpg?optimize=low&bg-color=255%2C255%2C255&fit=bounds&height=300&width=300"
          }
     }
     ]
}

####
GET http://localhost:3000/api/category?category=Snacks

######
GET http://localhost:3000/api/user/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwNTI0Mzg5NCwiZXhwIjoxNzA1MjQ3NDk0fQ.6CiQVHJ7FXHmVKiGcaNjIXekMYqHifX9PcreyO91wBw

########
POST http://localhost:3000/api/user/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwNTI0Mzg5NCwiZXhwIjoxNzA1MjQ3NDk0fQ.6CiQVHJ7FXHmVKiGcaNjIXekMYqHifX9PcreyO91wBw

{
     "name": "OTEN NI SATANAS",
     "schedule": "Monday",
     "items":[{
      "title": "Mondelez Oreo Vanilla Cookies | 27.6g 9pcs",
      "price": 80,
      "image_url": "https://smmarkets.ph/media/catalog/product/2/0/20232695_oreo_vanilla_27.6g_x_9_pcs_copy_.png?optimize=low&bg-color=255%2C255%2C255&fit=bounds&height=300&width=300"
    },
    {
      "title": "Mondelez Oreo Vanilla Cookies | 27.6g 9pcs",
      "price": 80,
      "image_url": "https://smmarkets.ph/media/catalog/product/2/0/20232695_oreo_vanilla_27.6g_x_9_pcs_copy_.png?optimize=low&bg-color=255%2C255%2C255&fit=bounds&height=300&width=300"
    },
    {
      "title": "Mondelez Oreo Vanilla Cookies | 27.6g 9pcs",
      "price": 80,
      "image_url": "https://smmarkets.ph/media/catalog/product/2/0/20232695_oreo_vanilla_27.6g_x_9_pcs_copy_.png?optimize=low&bg-color=255%2C255%2C255&fit=bounds&height=300&width=300"
    }]
}


###
DELETE http://localhost:3000/api/user/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwNDk2NDUwNCwiZXhwIjoxNzA0OTY4MTA0fQ.mVFZRIGPas8w5KKAE1p2_G8kGNi4aLLtFeXZ1HmWcBQ

{
     "userId": "656c4d3aef4c2d379ceb0163",
     "itemId": "656d65a00106dd24076f86e2"
}


###
PUT http://localhost:3000/api/user/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwNTI0Mzg5NCwiZXhwIjoxNzA1MjQ3NDk0fQ.6CiQVHJ7FXHmVKiGcaNjIXekMYqHifX9PcreyO91wBw

{
     "userId": "656c4d3aef4c2d379ceb0163",
     "itemId": "65a3febe6486e0a8be14cce4",
     "items":[{
      "title": "Mondelez Oreo Vanilla Cookies | 27.6g 9pcs",
      "price": 80,
      "image_url": "https://smmarkets.ph/media/catalog/product/2/0/20232695_oreo_vanilla_27.6g_x_9_pcs_copy_.png?optimize=low&bg-color=255%2C255%2C255&fit=bounds&height=300&width=300"
    },
    {
      "title": "Mondelez Oreo Vanilla Cookies | 27.6g 9pcs",
      "price": 120,
      "image_url": "https://smmarkets.ph/media/catalog/product/2/0/20232695_oreo_vanilla_27.6g_x_9_pcs_copy_.png?optimize=low&bg-color=255%2C255%2C255&fit=bounds&height=300&width=300"
    }]
}


###
GET http://localhost:3000/api/search?item=Apple
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWVzIiwiaWF0IjoxNzAxMzk3MTE5fQ.-tKE2Yzk5L39H7HQEBxlNPWA45BN-_geafP4Lp6a9lM


######

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
     "email": "lenyajpatiarba@gmail.com",
     "password": "admin123"
}

######
GET http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWFkY2Y0YjAzZGE0ODVlZmEyNzE3YyIsImlhdCI6MTcwNTA5ODM4MSwiZXhwIjoxNzA1MTAxOTgxfQ.xoG2Bq-1jPl5jtxT0d1iSPkOB0D3ekSspo_4D0efM3s


#####
POST http://localhost:3000/api/user/create
Content-Type: application/json

{
     "first_name": "test",
     "last_name": "test",
     "email": "admin@gmail.com",
     "password": "admin123"
}

####

DELETE http://localhost:3000/api/user/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmI2MDNmYmNlNGUyNjJjZjc2ZjU3ZCIsImlhdCI6MTcwMTUzNTgxM30._TSBB5W8RsmXaN6X8lX-vp2F79rshI8m36OfdTZ4OKY

###

PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwMTU5NjQ4Mn0.61jDT10cJzEBBV6i6hTLQDJvKB-VlcSUV8ktMm3A68Y

{
     "password": "admin1234"
}
###
POST http://localhost:3000/api/user/send
Content-Type: application/json

{
     "email": "lenyajpatiarba@gmail.com"
}

####
POST http://localhost:3000/api/user/reset
Content-Type: application/json

{
     "email": "lenyajpatiarba@gmail.com",
     "password": "admin123",
     "otp": "748327"
}


####
GET http://localhost:3000/api/user/me/wishlist/share?id=656d64d09be7f4d376cdbc03
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM0ZDNhZWY0YzJkMzc5Y2ViMDE2MyIsImlhdCI6MTcwMTU5NjQ4Mn0.61jDT10cJzEBBV6i6hTLQDJvKB-VlcSUV8ktMm3A68Y

###

GET http://localhost:3000/api/category?localhost:3000/api/category